apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "overleaf.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "overleaf.labels" . | nindent 4 }}
data:
  OVERLEAF_MONGO_URL: mongodb://{{ include "overleaf.fullname" . }}-mongodb-headless/overleaf
  OVERLEAF_REDIS_HOST: {{ include "overleaf.fullname" . }}-redis-headless.{{ .Release.Namespace }}.svc.cluster.local
  REDIS_HOST: {{ include "overleaf.fullname" . }}-redis-headless.{{ .Release.Namespace }}.svc.cluster.local
  OVERLEAF_SITE_URL: https://{{ .Values.ingress.host }}
  OVERLEAF_SITE_NAME: Overleaf
  OVERLEAF_SITE_TITLE: Overleaf Collaborative LaTeX Editor
  OVERLEAF_SITE_DESCRIPTION: Collaborative cloud-based LaTeX editor
  ENABLED_LINKED_FILE_TYPES: "project_file,project_output,project_output_log"
  SIBLING_CONTAINERS_ENABLED: "false"
  SERVER_PRO: "true"
  {{- with .Values.overleafExtraConfig }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
