apiVersion: v1
kind: Secret
metadata:
  name: {{ include "overleaf.fullname" . }}-smtp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "overleaf.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.smtp.secret.password | quote }}
  username: {{ .Values.smtp.secret.username | quote }}
