apiVersion: v1
kind: Service
metadata:
  name: {{ include "overleaf.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "overleaf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "overleaf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: overleaf
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: web
